# -*- coding: utf-8 -*-
"""
All text and data for NADRA HAMRAHI (prototype).

Everything the user reads lives here, in English (en) and Urdu (ur), so that
app.py stays about layout and behaviour only.

IMPORTANT: The curated answers below were written from NADRA's public pages
and public news reports. Fees are deliberately NOT quoted. Please proofread
the Urdu and re-check every answer against nadra.gov.pk before sharing widely.
"""

# ---------------------------------------------------------------------------
# Official contact details (shown in the footer; never generated by the AI)
# Source: https://www.nadra.gov.pk/contact and /complaints/
# ---------------------------------------------------------------------------
CONTACT = {
    "mobile": "1777",
    "landline": "+92 51 111 786 100",
    "email": "csd@nadra.gov.pk",
    "web": "nadra.gov.pk",
    "complaints": "complaints.nadra.gov.pk",
}

# ---------------------------------------------------------------------------
# Sources: key -> (label, url, type)   type: official | news | web
# ---------------------------------------------------------------------------
SOURCES = {
    "cnic": ("NADRA: CNIC page", "https://www.nadra.gov.pk/identityDocument/cnic", "official"),
    "contact": ("NADRA: Contact us", "https://www.nadra.gov.pk/contact", "official"),
    "complaints": ("NADRA: Complaints", "https://www.nadra.gov.pk/complaints/", "official"),
    "complaint_pr": (
        "NADRA: Complaint system announcement",
        "https://www.nadra.gov.pk/nadra-launches-centralized-complaint-management-system-for-citizens/",
        "official",
    ),
    "faqs": ("NADRA: FAQs", "https://www.nadra.gov.pk/faqs", "official"),
    "id_home": (
        "NADRA: Identity documents",
        "https://id.nadra.gov.pk/identity-documents/identity-nic/",
        "official",
    ),
    "pakid_faq": ("NADRA: PakID FAQs", "https://www.nadra.gov.pk/pakIdentityFaqs", "official"),
    "biometric_pr": (
        "NADRA: Biometric verification clarification",
        "https://www.nadra.gov.pk/mediaRelease/nadra-clarifies-biometric-verification-issues-7047157c",
        "official",
    ),
    "pension_geo": (
        "Geo News: NADRA to verify pensioners",
        "https://www.geo.tv/latest/681472-nadra-to-undertake-biometric-verification-of-pensioners",
        "news",
    ),
    "pension_nation": (
        "The Nation: pension verification moves to NADRA",
        "https://www.nation.com.pk/10-Sep-2026/govt-shifts-pension-biometric-verification-banks-nadra",
        "news",
    ),
    "pension_ausaf": (
        "Daily Ausaf: Proof of Life for pensioners",
        "https://dailyausaf.com/en/pakistan/nadra-makes-proof-of-life-certificate-free-for-pensioners/",
        "news",
    ),
    "face_news": (
        "The Current: face verification when fingerprints fail",
        "https://thecurrent.pk/unable-to-verify-your-fingerprints-with-nadra-heres-how-you-can-use-facial-recognition-instead",
        "news",
    ),
    "idtech": (
        "ID Tech: NADRA on biometric verification",
        "https://idtechwire.com/nadra-clarifies-biometric-verification-issues-emphasizes-system-functionality/",
        "news",
    ),
    "lost_guide": (
        "Community guide: lost or stolen CNIC",
        "https://imsidata.com/what-to-do-if-your-cnic-is-lost-or-stolen/",
        "web",
    ),
    "crc_guide": (
        "Community guide: B-Form rules",
        "https://pakistankibaat.pk/nadra-cnic-b-form-rules/",
        "web",
    ),
    "new_cnic_guide": (
        "Community guide: new CNIC application",
        "https://www.abnamro.com.pk/new-cnic-apply-documents/",
        "web",
    ),
}


def src(*keys):
    return [SOURCES[k] for k in keys]


# ---------------------------------------------------------------------------
# Interface text
# ---------------------------------------------------------------------------
UI = {
    "en": {
        "brand": "NADRA HAMRAHI",
        "nav_home": "Home",
        "nav_cnic": "CNIC",
        "nav_services": "Services",
        "nav_assistant": "Ask AI",
        "nav_how": "How it works",
        "nav_about": "About",
        "hero_title": "Ask about anything NADRA.",
        "hero_sub": "Pick your situation or type your question. Answers in English or Urdu.",
        "ask_ph": "Have a question about NADRA? Type it here",
        "ask_btn": "Ask",
        "popular_title": "Popular questions",
        "popular_sub": "Click a question and the assistant answers straight away.",
        "problems_title": "Common problems",
        "problems_sub": "Pick your problem and find out the next step.",
        "cnic_title": "CNIC: what do you need help with?",
        "cnic_sub": "Choose one. You can keep asking questions afterwards.",
        "services_title": "NADRA services",
        "services_sub": "A short introduction to each service. Ask the assistant for details.",
        "ask_about": "Ask about this",
        "assistant_title": "Ask the NADRA assistant",
        "topic": "Topic",
        "clear_topic": "Clear topic",
        "chat_ph": "Type your question...",
        "follow_title": "You can also ask",
        "start_hint": "Type a question below, or start with one of these.",
        "disclaimer": "Independent guide, not an official NADRA service. Confirm details with NADRA before you act.",
        "demo_notice": "Demo mode: no AI key is set, so this is the closest saved information. Add GROQ_API_KEY for live answers.",
        "limit_msg": "You have reached the AI question limit for this session. Reload the page, or call NADRA on 1777.",
        "busy_msg": "The AI is busy right now. Try again in a moment, or call NADRA on 1777.",
        "no_info": "I don't have saved information on that. Please ask NADRA directly: 1777 from a mobile, or +92 51 111 786 100 from a landline or abroad.",
        "id_removed": "Your message contained a number that looks like an ID or phone number. It was removed. Please never share ID numbers, tracking IDs or OTPs here.",
        "src_title": "Sources",
        "src_official": "Official NADRA",
        "src_news": "News report",
        "src_web": "Community website",
        "contact_title": "Official NADRA contacts",
        "contact_mobile": "Mobile (Pakistan)",
        "contact_landline": "Landline and overseas",
        "contact_email": "Email",
        "contact_web": "Website",
        "how_title": "How it works",
        "how_closing": "You don't have to know what to ask.",
        "how_closing_sub": "Choose your situation and let NADRA HAMRAHI guide you.",
        "about_title": "About NADRA HAMRAHI",
        "start_btn": "Start with a question",
        "send_btn": "Send",
        "record_btn": "Record voice",
        "stop_btn": "Stop and use this",
        "voice_note_ready": "Recording saved. Review the text below, then press Send.",
        "voice_note_need_key": "Voice input needs an AI key (GROQ_API_KEY) to convert speech to text.",
        "voice_note_missing_pkg": "Voice input isn't installed in this preview. See README.md to add it.",
        "voice_transcribing": "Converting your voice to text...",
    },
    "ur": {
        "brand": "نادرا ہمراہی",
        "nav_home": "ہوم",
        "nav_cnic": "شناختی کارڈ",
        "nav_services": "خدمات",
        "nav_assistant": "اے آئی سے پوچھیں",
        "nav_how": "طریقۂ کار",
        "nav_about": "ہمارے بارے میں",
        "hero_title": "نادرا سے متعلق کچھ بھی پوچھیں۔",
        "hero_sub": "اپنی صورتحال چنیں یا اپنا سوال لکھیں۔ جواب اردو یا انگریزی میں ملے گا۔",
        "ask_ph": "نادرا کے بارے میں اپنا سوال یہاں لکھیں",
        "ask_btn": "پوچھیں",
        "popular_title": "عام سوالات",
        "popular_sub": "کسی سوال پر کلک کریں، اسسٹنٹ فوراً جواب دے گا۔",
        "problems_title": "عام مسائل",
        "problems_sub": "اپنا مسئلہ چنیں اور اگلا قدم جانیں۔",
        "cnic_title": "شناختی کارڈ: آپ کو کس بارے میں مدد چاہیے؟",
        "cnic_sub": "ایک چنیں۔ اس کے بعد آپ مزید سوال بھی پوچھ سکتے ہیں۔",
        "services_title": "نادرا کی خدمات",
        "services_sub": "ہر خدمت کا مختصر تعارف۔ تفصیل کے لیے اسسٹنٹ سے پوچھیں۔",
        "ask_about": "اس بارے میں پوچھیں",
        "assistant_title": "نادرا اسسٹنٹ سے پوچھیں",
        "topic": "موضوع",
        "clear_topic": "موضوع ہٹائیں",
        "chat_ph": "اپنا سوال لکھیں...",
        "follow_title": "آپ یہ بھی پوچھ سکتے ہیں",
        "start_hint": "نیچے سوال لکھیں، یا ان میں سے کسی سے شروع کریں۔",
        "disclaimer": "یہ ایک آزاد رہنما ہے، نادرا کی سرکاری سروس نہیں۔ کوئی قدم اٹھانے سے پہلے نادرا سے تصدیق کر لیں۔",
        "demo_notice": "ڈیمو موڈ: اے آئی کی کلید سیٹ نہیں، اس لیے محفوظ شدہ سب سے متعلقہ معلومات دکھائی جا رہی ہیں۔ لائیو جوابات کے لیے GROQ_API_KEY شامل کریں۔",
        "limit_msg": "اس سیشن میں اے آئی سوالات کی حد پوری ہو گئی ہے۔ صفحہ دوبارہ کھولیں، یا نادرا کو 1777 پر کال کریں۔",
        "busy_msg": "اے آئی اس وقت مصروف ہے۔ کچھ دیر بعد دوبارہ کوشش کریں، یا نادرا کو 1777 پر کال کریں۔",
        "no_info": "اس بارے میں میرے پاس محفوظ معلومات نہیں ہیں۔ براہِ کرم نادرا سے براہِ راست پوچھیں: موبائل سے 1777، یا لینڈ لائن اور بیرونِ ملک سے +92 51 111 786 100۔",
        "id_removed": "آپ کے پیغام میں شناختی کارڈ یا فون نمبر جیسا ہندسہ تھا، اسے ہٹا دیا گیا ہے۔ براہِ کرم یہاں شناختی نمبر، ٹریکنگ نمبر یا او ٹی پی شیئر نہ کریں۔",
        "src_title": "ذرائع",
        "src_official": "نادرا (سرکاری)",
        "src_news": "خبری رپورٹ",
        "src_web": "کمیونٹی ویب سائٹ",
        "contact_title": "نادرا کے سرکاری رابطے",
        "contact_mobile": "موبائل (پاکستان)",
        "contact_landline": "لینڈ لائن اور بیرونِ ملک",
        "contact_email": "ای میل",
        "contact_web": "ویب سائٹ",
        "how_title": "یہ کیسے کام کرتا ہے",
        "how_closing": "آپ کو یہ جاننے کی ضرورت نہیں کہ کیا پوچھنا ہے۔",
        "how_closing_sub": "اپنی صورتحال چنیں اور نادرا ہمراہی کو رہنمائی کرنے دیں۔",
        "about_title": "نادرا ہمراہی کے بارے میں",
        "start_btn": "سوال سے شروع کریں",
        "send_btn": "بھیجیں",
        "record_btn": "آواز ریکارڈ کریں",
        "stop_btn": "روکیں اور استعمال کریں",
        "voice_note_ready": "ریکارڈنگ محفوظ ہو گئی۔ نیچے تحریر دیکھیں، پھر بھیجیں دبائیں۔",
        "voice_note_need_key": "آواز کو تحریر میں بدلنے کے لیے اے آئی کلید (GROQ_API_KEY) درکار ہے۔",
        "voice_note_missing_pkg": "اس پیش نظارے میں آواز کی سہولت شامل نہیں۔ تفصیل کے لیے README.md دیکھیں۔",
        "voice_transcribing": "آپ کی آواز کو تحریر میں بدلا جا رہا ہے...",
    },
}

GREETING = {
    "en": "We can converse in English.",
    "ur": "ہم اردو میں بات کر سکتے ہیں۔",
}

TICKER = {
    "en": [
        "Independent guide, not an official NADRA service",
        "For official help, call NADRA on 1777",
        "Ask your question in English or Urdu",
        "Never share your ID number, tracking ID or OTP here",
    ],
    "ur": [
        "یہ ایک آزاد رہنما ہے، نادرا کی سرکاری سروس نہیں",
        "سرکاری مدد کے لیے نادرا کو 1777 پر کال کریں",
        "اپنا سوال اردو یا انگریزی میں پوچھیں",
        "یہاں اپنا شناختی نمبر، ٹریکنگ آئی ڈی یا او ٹی پی کبھی نہ لکھیں",
    ],
}

HOW_STEPS = [
    {
        "title": {"en": "Choose your situation", "ur": "اپنی صورتحال چنیں"},
        "text": {
            "en": "Select a common question, service or problem.",
            "ur": "کوئی عام سوال، خدمت یا مسئلہ چنیں۔",
        },
    },
    {
        "title": {"en": "Get relevant guidance", "ur": "متعلقہ رہنمائی حاصل کریں"},
        "text": {
            "en": "You get information for that situation only, with its sources.",
            "ur": "آپ کو صرف اسی صورتحال کی معلومات اور اس کے ذرائع ملتے ہیں۔",
        },
    },
    {
        "title": {"en": "Answer a few questions", "ur": "چند سوالوں کے جواب دیں"},
        "text": {
            "en": "Tap the follow-up options so the answer fits your case.",
            "ur": "مزید سوالات کے آپشن دبائیں تاکہ جواب آپ کے کیس کے مطابق ہو۔",
        },
    },
    {
        "title": {"en": "Ask follow-up questions", "ur": "مزید سوال پوچھیں"},
        "text": {
            "en": "Keep chatting in English or Urdu. You never have to go back to the menu.",
            "ur": "اردو یا انگریزی میں بات جاری رکھیں۔ مینو پر واپس جانا ضروری نہیں۔",
        },
    },
    {
        "title": {"en": "Find your next step", "ur": "اگلا قدم جانیں"},
        "text": {
            "en": "Learn what NADRA asks for and where to find official information.",
            "ur": "جانیں کہ نادرا کو کیا درکار ہے اور سرکاری معلومات کہاں ملیں گی۔",
        },
    },
]

ABOUT = {
    "en": """
**What is NADRA HAMRAHI?**
An AI-powered guide that makes NADRA information easier to find and understand.

**Why we built it**
People usually know their problem, but not which service they need, which documents are required,
what a NADRA term means, or how to phrase the question.

**What it does**
- Gives guided information for your situation
- Answers follow-up questions in English or Urdu
- Shows the sources behind each answer

**What it does not do**
- It cannot track applications, look up your record, or calculate your personal fees
- It never needs your ID number, tracking ID, password or OTP

**Important**
NADRA HAMRAHI is an independent informational assistant, not an official NADRA service.
Applications, payments, verification and official complaints must go through NADRA's official channels.

**Prototype note**
Answers use publicly available information, including news reports and community websites,
and may be out of date. Official NADRA sources always come first.
""",
    "ur": """
**نادرا ہمراہی کیا ہے؟**
ایک اے آئی رہنما جو نادرا کی معلومات کو تلاش کرنا اور سمجھنا آسان بناتا ہے۔

**ہم نے اسے کیوں بنایا**
لوگ عموماً اپنا مسئلہ جانتے ہیں، مگر یہ نہیں جانتے کہ کون سی خدمت چاہیے، کون سے کاغذات درکار ہیں،
نادرا کی کسی اصطلاح کا کیا مطلب ہے، یا سوال کیسے پوچھیں۔

**یہ کیا کرتا ہے**
- آپ کی صورتحال کے مطابق رہنمائی دیتا ہے
- اردو یا انگریزی میں مزید سوالوں کے جواب دیتا ہے
- ہر جواب کے ذرائع دکھاتا ہے

**یہ کیا نہیں کرتا**
- یہ درخواستوں کو ٹریک نہیں کر سکتا، آپ کا ریکارڈ نہیں دیکھ سکتا، اور آپ کی ذاتی فیس کا حساب نہیں لگاتا
- اسے آپ کے شناختی نمبر، ٹریکنگ آئی ڈی، پاس ورڈ یا او ٹی پی کی کبھی ضرورت نہیں

**اہم بات**
نادرا ہمراہی ایک آزاد معلوماتی اسسٹنٹ ہے، نادرا کی سرکاری سروس نہیں۔
درخواستیں، ادائیگیاں، تصدیق اور سرکاری شکایات نادرا کے سرکاری ذرائع سے ہی کی جائیں۔

**پروٹوٹائپ سے متعلق نوٹ**
جوابات عوامی طور پر دستیاب معلومات پر مبنی ہیں، جن میں خبری رپورٹس اور کمیونٹی ویب سائٹس بھی شامل ہیں،
اس لیے یہ پرانی ہو سکتی ہیں۔ سرکاری نادرا ذرائع کو ہمیشہ ترجیح حاصل ہے۔
""",
}

# ---------------------------------------------------------------------------
# Topics. Each topic can have:
#   title, question (auto-sent when the card is clicked), answer (curated,
#   costs zero AI tokens), chips (follow-up questions), sources, kw (keywords
#   used by the simple search that finds context for the AI).
# ---------------------------------------------------------------------------
TOPICS = {
    # ------------------------------------------------------------ popular
    "first-cnic": {
        "title": {"en": "First-time CNIC", "ur": "پہلا شناختی کارڈ"},
        "question": {
            "en": "How do I get my first CNIC?",
            "ur": "میں اپنا پہلا شناختی کارڈ کیسے بنواؤں؟",
        },
        "kw": ["first cnic", "new cnic", "first time", "apply", "first", "پہلا", "پہلی", "نیا شناختی", "بنوا"],
        "answer": {
            "en": """Adult Pakistani citizens (18 and over) apply for their first CNIC. Under 18, the identity document is the CRC (B-Form).

**What NADRA's public CNIC page lists:**
- A computerised birth certificate (from the Union Council, Municipal Committee or Cantonment), or a citizenship / naturalization certificate
- The ID card number of a parent or blood relative, who verifies you with their biometrics
- If you have no blood relative, NADRA mentions a biometric witness (an ID card holder) with a signed undertaking, in some cases only
- Your own fingerprints and photo, usually taken at a NADRA Registration Centre

You can start through the PakID app, but the photo and biometrics may still need a centre visit.""",
            "ur": """پاکستانی بالغ شہری (18 سال اور اس سے اوپر) پہلا شناختی کارڈ بنواتے ہیں۔ 18 سال سے کم عمر کے لیے شناختی دستاویز سی آر سی (ب فارم) ہے۔

**نادرا کے عوامی صفحے پر عموماً یہ درج ہے:**
- کمپیوٹرائزڈ برتھ سرٹیفکیٹ (یونین کونسل، میونسپل کمیٹی یا کنٹونمنٹ کی طرف سے)، یا شہریت / نیچرلائزیشن سرٹیفکیٹ
- والدین یا خونی رشتہ دار کا شناختی کارڈ نمبر، جو اپنی بایومیٹرک تصدیق سے آپ کی شناخت کی تصدیق کرتا ہے
- اگر کوئی خونی رشتہ دار نہ ہو تو نادرا بعض صورتوں میں شناختی کارڈ رکھنے والے گواہ کی بایومیٹرک تصدیق اور دستخط شدہ انڈرٹیکنگ کا ذکر کرتا ہے
- آپ کی اپنی انگلیوں کے نشانات اور تصویر، جو عموماً نادرا رجسٹریشن سینٹر میں لی جاتی ہے

آپ پاک آئی ڈی ایپ سے آغاز کر سکتے ہیں، لیکن تصویر اور بایومیٹرک کے لیے سینٹر جانا پڑ سکتا ہے۔""",
        },
        "chips": {
            "en": [
                "What if I don't have a birth certificate?",
                "Do I have to go to a centre in person?",
                "Who can verify me?",
            ],
            "ur": [
                "اگر میرے پاس برتھ سرٹیفکیٹ نہ ہو تو؟",
                "کیا مجھے سینٹر خود جانا ہوگا؟",
                "میری تصدیق کون کر سکتا ہے؟",
            ],
        },
        "sources": src("cnic", "id_home"),
    },
    "fees-processing": {
        "title": {"en": "Fees and processing time", "ur": "فیس اور پروسیسنگ کا وقت"},
        "question": {
            "en": "What are the fees and processing times?",
            "ur": "فیس اور پروسیسنگ کا وقت کتنا ہے؟",
        },
        "kw": ["fee", "fees", "cost", "price", "charge", "how much", "processing time", "urgent", "executive",
               "فیس", "قیمت", "لاگت", "کتنا", "کتنی", "پروسیسنگ", "خرچ"],
        "answer": {
            "en": """Fees and processing times depend on the service and the speed you choose (for example normal, urgent or executive), and NADRA changes them from time to time.

NADRA publishes the current amounts on the page of each service (look for the link about the updated fee and processing time). This assistant does not quote fees or calculate costs for you.

Before you pay, check NADRA's official page or call 1777. Pay only through NADRA's official channels.""",
            "ur": """فیس اور پروسیسنگ کا وقت خدمت کی قسم اور آپ کی منتخب کردہ رفتار (مثلاً نارمل، ارجنٹ یا ایگزیکٹو) پر منحصر ہے، اور نادرا وقتاً فوقتاً انہیں تبدیل کرتا ہے۔

نادرا ہر خدمت کے صفحے پر موجودہ فیس اور پروسیسنگ کا وقت شائع کرتا ہے (اپ ڈیٹ شدہ فیس اور وقت والا لنک دیکھیں)۔ یہ اسسٹنٹ فیس نہیں بتاتا اور نہ آپ کے لیے لاگت کا حساب لگاتا ہے۔

ادائیگی سے پہلے نادرا کا سرکاری صفحہ دیکھیں یا 1777 پر کال کریں۔ ادائیگی صرف نادرا کے سرکاری ذرائع سے کریں۔""",
        },
        "chips": {
            "en": ["Where do I find the official fee page?", "How can I check my application status?"],
            "ur": ["سرکاری فیس کا صفحہ کہاں ملے گا؟", "میں اپنی درخواست کی صورتحال کیسے دیکھوں؟"],
        },
        "sources": src("cnic", "contact"),
    },
    "documents": {
        "title": {"en": "Required documents", "ur": "مطلوبہ کاغذات"},
        "question": {"en": "What documents do I need?", "ur": "مجھے کون سے کاغذات درکار ہیں؟"},
        "kw": ["document", "documents", "paper", "required", "requirement", "what do i need",
               "کاغذ", "کاغذات", "دستاویز", "درکار", "ضرورت"],
        "answer": {
            "en": """The documents depend on what you are applying for. Common items on NADRA's public pages:
- A computerised birth certificate, or a citizenship certificate
- ID card numbers of parents or blood relatives
- Your existing CNIC, for renewal, reprint or modification
- Supporting papers when details change (for example a marriage certificate for marital status)

Tell me the service, for example "renew my CNIC", and I'll share what NADRA publishes for it.""",
            "ur": """درکار کاغذات اس پر منحصر ہیں کہ آپ کس خدمت کے لیے درخواست دے رہے ہیں۔ نادرا کے عوامی صفحات پر عام طور پر یہ چیزیں آتی ہیں:
- کمپیوٹرائزڈ برتھ سرٹیفکیٹ، یا شہریت کا سرٹیفکیٹ
- والدین یا خونی رشتہ داروں کے شناختی کارڈ نمبر
- تجدید، ری پرنٹ یا ترمیم کے لیے آپ کا موجودہ شناختی کارڈ
- تفصیلات بدلنے پر معاون کاغذات (مثلاً ازدواجی حیثیت کے لیے نکاح نامہ)

مجھے خدمت بتائیں، مثلاً "شناختی کارڈ کی تجدید"، میں اس کے لیے نادرا کی شائع کردہ معلومات بتا دوں گا۔""",
        },
        "chips": {
            "en": ["What documents do I need for renewal?", "What is needed for a child's B-Form?"],
            "ur": ["تجدید کے لیے کون سے کاغذات چاہییں؟", "بچے کے ب فارم کے لیے کیا چاہیے؟"],
        },
        "sources": src("cnic", "id_home"),
    },
    "biometric-iris": {
        "title": {"en": "Biometric and iris verification", "ur": "بایومیٹرک اور آئرس تصدیق"},
        "question": {
            "en": "Why am I being asked for biometric or iris verification?",
            "ur": "مجھ سے بایومیٹرک یا آئرس تصدیق کیوں مانگی جا رہی ہے؟",
        },
        "kw": ["biometric", "iris", "fingerprint", "face", "facial", "verification", "why",
               "بایومیٹرک", "آئرس", "انگلی", "انگلیوں", "تصدیق", "چہرے"],
        "answer": {
            "en": """NADRA matches your fingerprints, face or iris against the record made when you got your ID. The point is to confirm that you really are you.

It is used when you apply for or change an ID document, and when banks, mobile companies or property offices verify you through NADRA.

Fingerprints wear down with age or manual work, so news reports say NADRA has made face and iris matching recognised alternatives. If verification fails, see the topic "My biometric verification isn't working".""",
            "ur": """نادرا آپ کی انگلیوں کے نشانات، چہرے یا آئرس کو اس ریکارڈ سے ملاتا ہے جو شناختی کارڈ بنواتے وقت محفوظ ہوا تھا۔ مقصد یہ تصدیق کرنا ہے کہ آپ واقعی وہی شخص ہیں۔

یہ تصدیق شناختی دستاویز کے لیے درخواست دینے یا اس میں تبدیلی کرتے وقت، اور بینک، موبائل کمپنی یا جائیداد کے دفاتر میں آپ کی شناخت جانچنے کے لیے کی جاتی ہے۔

عمر یا محنت مزدوری سے انگلیوں کے نشانات گھس جاتے ہیں، اس لیے خبروں کے مطابق نادرا نے چہرے اور آئرس کی تصدیق کو بھی تسلیم شدہ متبادل بنایا ہے۔ اگر تصدیق ناکام ہو تو "میری بایومیٹرک تصدیق نہیں ہو رہی" والا موضوع دیکھیں۔""",
        },
        "chips": {
            "en": ["What if my fingerprints don't match?", "Can I use face verification instead?"],
            "ur": ["اگر میری انگلیوں کے نشانات نہ ملیں تو؟", "کیا میں چہرے سے تصدیق کروا سکتا ہوں؟"],
        },
        "sources": src("biometric_pr", "idtech", "face_news"),
    },
    "id-types": {
        "title": {"en": "CNIC, NICOP or POC", "ur": "سی این آئی سی، نکوپ یا پی او سی"},
        "question": {"en": "Which identity card is for me?", "ur": "میرے لیے کون سا شناختی کارڈ ہے؟"},
        "kw": ["nicop", "poc", "crc", "frc", "b-form", "b form", "origin card", "overseas", "which card",
               "نکوپ", "اوریجن", "ب فارم", "ایف آر سی", "کون سا کارڈ"],
        "answer": {
            "en": """- **CNIC:** the identity card for adult Pakistani citizens.
- **NICOP:** for Pakistani citizens living abroad.
- **POC (Pakistan Origin Card):** for people of Pakistani origin who are not Pakistani citizens.
- **CRC (B-Form):** the registration certificate for children under 18.
- **FRC:** a certificate listing family members registered together with NADRA.

Which one fits depends on your citizenship and where you live. Tell me your situation and I'll narrow it down.""",
            "ur": """- **سی این آئی سی:** پاکستانی بالغ شہریوں کا شناختی کارڈ۔
- **نکوپ (NICOP):** بیرونِ ملک رہنے والے پاکستانی شہریوں کے لیے۔
- **پی او سی (پاکستان اوریجن کارڈ):** ان لوگوں کے لیے جو پاکستانی نژاد ہیں مگر پاکستانی شہری نہیں۔
- **سی آر سی (ب فارم):** 18 سال سے کم عمر بچوں کی رجسٹریشن کا سرٹیفکیٹ۔
- **ایف آر سی:** نادرا میں ایک ساتھ رجسٹرڈ خاندان کے افراد کی فہرست پر مبنی سرٹیفکیٹ۔

کون سا آپ کے لیے ہے، یہ آپ کی شہریت اور رہائش پر منحصر ہے۔ اپنی صورتحال بتائیں، میں دائرہ محدود کر دوں گا۔""",
        },
        "chips": {
            "en": ["I live abroad. Which card do I need?", "What is an FRC used for?"],
            "ur": ["میں بیرونِ ملک رہتا ہوں، مجھے کون سا کارڈ چاہیے؟", "ایف آر سی کس کام آتا ہے؟"],
        },
        "sources": src("id_home", "cnic"),
    },
    "pensioner": {
        "title": {"en": "Pensioner assistance", "ur": "پنشنرز کے لیے مدد"},
        "question": {
            "en": "What NADRA services are there for pensioners?",
            "ur": "پنشنرز کے لیے نادرا کی کون سی خدمات ہیں؟",
        },
        "kw": ["pension", "pensioner", "proof of life", "life certificate", "پنشن", "پنشنر", "پروف آف لائف", "زندہ"],
        "answer": {
            "en": """Pensioners must prove they are alive (Proof of Life). According to news reports from September 2026, NADRA now handles this verification directly instead of banks.
- Verification is needed at least once every six months (180 days)
- It can be done through the Pak-ID app, NADRA Registration Centres, mobile units or e-Sahulat franchises
- Banks should point you to NADRA rather than collect your biometrics
- If your fingerprints won't verify because of age, ask NADRA about face-based verification

This system is new, so confirm the details with NADRA on 1777.""",
            "ur": """پنشنرز کو ثابت کرنا ہوتا ہے کہ وہ زندہ ہیں (پروف آف لائف)۔ ستمبر 2026 کی خبروں کے مطابق اب یہ تصدیق بینکوں کے بجائے براہِ راست نادرا کرتا ہے۔
- کم از کم ہر چھ ماہ (180 دن) میں ایک بار تصدیق ضروری ہے
- یہ پاک آئی ڈی ایپ، نادرا رجسٹریشن سینٹرز، موبائل یونٹس یا ای-سہولت فرنچائزز کے ذریعے ہو سکتی ہے
- بینکوں کو چاہیے کہ آپ سے بایومیٹرک لینے کے بجائے آپ کو نادرا کی طرف رہنمائی دیں
- اگر عمر کی وجہ سے انگلیوں کے نشانات نہ ملیں تو نادرا سے چہرے کی تصدیق کے بارے میں پوچھیں

یہ نظام نیا ہے، اس لیے تفصیل نادرا سے 1777 پر تصدیق کر لیں۔""",
        },
        "chips": {
            "en": ["Can a family member help with Proof of Life?", "What if I can't go to a centre?"],
            "ur": ["کیا خاندان کا کوئی فرد پروف آف لائف میں مدد کر سکتا ہے؟", "اگر میں سینٹر نہ جا سکوں تو؟"],
        },
        "sources": src("pension_geo", "pension_nation"),
    },
    # ----------------------------------------------------------- problems
    "rejected": {
        "title": {"en": "Application rejected", "ur": "درخواست مسترد"},
        "question": {
            "en": "My NADRA application was rejected. What should I do?",
            "ur": "میری نادرا درخواست مسترد ہو گئی ہے۔ مجھے کیا کرنا چاہیے؟",
        },
        "kw": ["reject", "rejected", "rejection", "رد", "مسترد"],
        "answer": {
            "en": """Applications are commonly rejected because a document is missing, names or dates don't match across documents, a parent's CNIC has expired, or verification (a parent's biometrics, for example) did not succeed.

**Next steps:**
1. Note the exact reason the centre or PakID gives you
2. Fix that item, for example get the missing document or correct the spelling mismatch
3. Apply again
4. If you believe the decision is wrong, call 1777 or file a complaint at complaints.nadra.gov.pk with your tracking ID

This assistant cannot see your application.""",
            "ur": """درخواست عموماً اس وجہ سے مسترد ہوتی ہے کہ کوئی کاغذ مکمل نہیں، کاغذات میں نام یا تاریخ مختلف ہے، والدین کا شناختی کارڈ ایکسپائر ہے، یا تصدیق (مثلاً والدین کی بایومیٹرک) کامیاب نہیں ہوئی۔

**اگلے قدم:**
1. سینٹر یا پاک آئی ڈی کی طرف سے بتائی گئی درست وجہ نوٹ کریں
2. وہی چیز درست کریں، مثلاً غائب کاغذ حاصل کریں یا نام کے ہجے کا فرق ٹھیک کروائیں
3. دوبارہ درخواست دیں
4. اگر آپ کو لگے کہ فیصلہ غلط ہے تو 1777 پر کال کریں یا اپنی ٹریکنگ آئی ڈی کے ساتھ complaints.nadra.gov.pk پر شکایت درج کریں

یہ اسسٹنٹ آپ کی درخواست نہیں دیکھ سکتا۔""",
        },
        "chips": {
            "en": ["How do I file a complaint?", "What are common rejection reasons?"],
            "ur": ["میں شکایت کیسے درج کروں؟", "مسترد ہونے کی عام وجوہات کیا ہیں؟"],
        },
        "sources": src("contact", "complaints"),
    },
    "refused": {
        "title": {"en": "Service refused", "ur": "سروس سے انکار"},
        "question": {
            "en": "A NADRA centre refused to provide my service. What can I do?",
            "ur": "نادرا سینٹر نے مجھے سروس دینے سے انکار کر دیا ہے۔ میں کیا کر سکتا ہوں؟",
        },
        "kw": ["refuse", "refused", "denied", "not provide", "انکار"],
        "answer": {
            "en": """If a centre refuses a service, first ask the officer to tell you exactly which requirement is not met. It is usually a missing document, an expired parent's ID, or a data mismatch.

**Then:**
- Fix the problem and go back
- If the service is available on the PakID app, try applying there
- If you think the refusal was wrong, or you were treated badly, complain through 1777, csd@nadra.gov.pk or complaints.nadra.gov.pk. Write down the centre name, date, time and what happened

NADRA says complaints are logged in one central system and escalated if they are not resolved in time.""",
            "ur": """اگر سینٹر سروس دینے سے انکار کرے تو پہلے اہلکار سے پوچھیں کہ کون سی شرط پوری نہیں ہو رہی۔ عموماً وجہ کوئی غائب کاغذ، ایکسپائر شدہ والدین کا کارڈ یا ڈیٹا میں فرق ہوتی ہے۔

**پھر:**
- مسئلہ درست کریں اور دوبارہ جائیں
- اگر خدمت پاک آئی ڈی ایپ پر دستیاب ہو تو وہاں درخواست دیں
- اگر آپ سمجھتے ہیں کہ انکار غلط تھا یا رویہ نامناسب تھا تو 1777، csd@nadra.gov.pk یا complaints.nadra.gov.pk پر شکایت کریں۔ سینٹر کا نام، تاریخ، وقت اور واقعہ لکھ لیں

نادرا کے مطابق شکایات ایک مرکزی نظام میں درج ہوتی ہیں اور بروقت حل نہ ہونے پر آگے بھیجی جاتی ہیں۔""",
        },
        "chips": {
            "en": ["What should I write in a complaint?", "Which document is usually the problem?"],
            "ur": ["شکایت میں کیا لکھنا چاہیے؟", "عموماً کون سا کاغذ مسئلہ بنتا ہے؟"],
        },
        "sources": src("contact", "complaints", "complaint_pr"),
    },
    "delayed": {
        "title": {"en": "Application delayed", "ur": "درخواست میں تاخیر"},
        "question": {
            "en": "My application is delayed or stuck. What can I do?",
            "ur": "میری درخواست میں تاخیر ہو رہی ہے یا رکی ہوئی ہے۔ میں کیا کروں؟",
        },
        "kw": ["delay", "delayed", "stuck", "pending", "late", "status", "track", "تاخیر", "رکی", "پھنس", "انتظار", "سٹیٹس"],
        "answer": {
            "en": """This assistant cannot see or track any application. To check yours:
- Log in to the application inbox in the PakID app (NADRA's contact page points there)
- Or call 1777 with your tracking ID ready

If the timeframe shown for your service has passed, file a complaint at complaints.nadra.gov.pk or email csd@nadra.gov.pk with your tracking ID. NADRA says complaints that stay unresolved are escalated.""",
            "ur": """یہ اسسٹنٹ کسی درخواست کو دیکھ یا ٹریک نہیں کر سکتا۔ اپنی درخواست کی صورتحال دیکھنے کے لیے:
- پاک آئی ڈی ایپ میں اپنے ایپلیکیشن ان باکس میں لاگ ان کریں (نادرا کے رابطہ صفحے پر یہی بتایا گیا ہے)
- یا اپنی ٹریکنگ آئی ڈی تیار رکھ کر 1777 پر کال کریں

اگر آپ کی خدمت کے لیے بتایا گیا وقت گزر چکا ہے تو ٹریکنگ آئی ڈی کے ساتھ complaints.nadra.gov.pk پر شکایت کریں یا csd@nadra.gov.pk پر ای میل کریں۔ نادرا کے مطابق حل نہ ہونے والی شکایات اوپر بھیجی جاتی ہیں۔""",
        },
        "chips": {
            "en": ["How long should it take?", "How do I file a complaint?"],
            "ur": ["اس میں کتنا وقت لگنا چاہیے؟", "میں شکایت کیسے درج کروں؟"],
        },
        "sources": src("contact", "complaint_pr"),
    },
    "verify-problem": {
        "title": {"en": "Biometric verification problems", "ur": "بایومیٹرک تصدیق کے مسائل"},
        "question": {
            "en": "My CNIC or biometric verification is failing. What should I do?",
            "ur": "میرے شناختی کارڈ یا بایومیٹرک کی تصدیق ناکام ہو رہی ہے۔ مجھے کیا کرنا چاہیے؟",
        },
        "kw": ["cannot verify", "can't verify", "not verified", "mismatch", "not matching", "failed", "not working",
               "ناکام", "نہیں مل", "نہیں ہو رہی", "نہیں ہو پا"],
        "answer": {
            "en": """If fingerprint verification fails (at NADRA, a bank or a mobile company):
1. Clean and dry your hands, press firmly, and try different fingers
2. If the device seems poor, try another franchise or centre
3. In the PakID app: good light, plain background, fingertips inside the boxes
4. Visit a NADRA Registration Centre. Reports say NADRA offers alternative verification for people whose fingerprints won't verify, including face-based options. Ask what is available for you
5. If your fingerprints have changed a lot, ask about updating your biometric record

**NADRA support:** 1777 from a mobile, +92 51 111 786 100 from a landline or abroad, csd@nadra.gov.pk. Never share your OTP and never pay an agent to fix this.""",
            "ur": """اگر انگلیوں کے نشانات کی تصدیق ناکام ہو (نادرا، بینک یا موبائل کمپنی پر):
1. ہاتھ صاف اور خشک کریں، انگلی مضبوطی سے رکھیں اور دوسری انگلیاں آزما کر دیکھیں
2. اگر مشین خراب لگے تو دوسری فرنچائز یا سینٹر آزمائیں
3. پاک آئی ڈی ایپ میں: اچھی روشنی، سادہ پس منظر، اور انگلیاں دیے گئے خانوں کے اندر رکھیں
4. نادرا رجسٹریشن سینٹر جائیں۔ رپورٹس کے مطابق نادرا ان لوگوں کے لیے متبادل تصدیق دیتا ہے جن کی انگلیوں کے نشانات نہیں ملتے، جن میں چہرے کی تصدیق شامل ہے۔ پوچھیں آپ کے لیے کیا دستیاب ہے
5. اگر آپ کے نشانات بہت بدل گئے ہیں تو بایومیٹرک ریکارڈ اپ ڈیٹ کروانے کے بارے میں پوچھیں

**نادرا سپورٹ:** موبائل سے 1777، لینڈ لائن اور بیرونِ ملک سے +92 51 111 786 100، ای میل csd@nadra.gov.pk۔ اپنا او ٹی پی کسی کو نہ بتائیں اور مسئلہ حل کرنے کے لیے کسی ایجنٹ کو پیسے نہ دیں۔""",
        },
        "chips": {
            "en": ["What is NADRA customer support?", "Can I use face verification instead?"],
            "ur": ["نادرا کسٹمر سپورٹ کیا ہے؟", "کیا میں چہرے سے تصدیق کروا سکتا ہوں؟"],
        },
        "sources": src("biometric_pr", "idtech", "face_news", "contact"),
    },
    "missing-doc": {
        "title": {"en": "Missing document", "ur": "مطلوبہ کاغذ موجود نہیں"},
        "question": {
            "en": "I don't have a required document. What are my options?",
            "ur": "میرے پاس مطلوبہ کاغذ نہیں ہے۔ میرے پاس کیا راستے ہیں؟",
        },
        "kw": ["missing", "don't have", "do not have", "lost document", "no birth", "کاغذ نہیں", "موجود نہیں"],
        "answer": {
            "en": """Don't assume you're stuck. NADRA lists alternatives for some documents.
- For a first CNIC, NADRA's public page accepts a computerised birth certificate **or** a citizenship certificate, and identifies you through a parent or blood relative
- If you have no blood relative, some cases allow an ID card holder as a biometric witness with an undertaking
- A missing paper is normally re-obtained from the office that issued it (a birth certificate from the Union Council, for example)

Ask the centre which alternative applies to your case, then go back with the paper. Tell me which document you're missing and I'll be more specific.""",
            "ur": """پریشان نہ ہوں، بعض کاغذات کے متبادل نادرا کی فہرست میں موجود ہیں۔
- پہلے شناختی کارڈ کے لیے نادرا کا عوامی صفحہ کمپیوٹرائزڈ برتھ سرٹیفکیٹ **یا** شہریت کا سرٹیفکیٹ قبول کرتا ہے، اور شناخت والدین یا خونی رشتہ دار کے ذریعے ہوتی ہے
- اگر کوئی خونی رشتہ دار نہ ہو تو بعض صورتوں میں شناختی کارڈ رکھنے والا گواہ اور انڈرٹیکنگ درکار ہوتی ہے
- گمشدہ کاغذ عموماً اسی ادارے سے دوبارہ حاصل کیا جاتا ہے جس نے جاری کیا تھا (مثلاً برتھ سرٹیفکیٹ یونین کونسل سے)

سینٹر سے پوچھیں کہ آپ کے کیس میں کون سا متبادل لاگو ہوتا ہے، پھر کاغذ لے کر جائیں۔ بتائیں کون سا کاغذ نہیں ہے، میں اس کے مطابق واضح بتاؤں گا۔""",
        },
        "chips": {
            "en": ["Where do I get a birth certificate?", "My parent's CNIC has expired"],
            "ur": ["برتھ سرٹیفکیٹ کہاں سے ملے گا؟", "میرے والد یا والدہ کا کارڈ ایکسپائر ہو گیا ہے"],
        },
        "sources": src("cnic"),
    },
    "no-cnic": {
        "title": {"en": "No CNIC available", "ur": "شناختی کارڈ دستیاب نہیں"},
        "question": {
            "en": "I don't have my CNIC and I need it. What can I do?",
            "ur": "میرے پاس شناختی کارڈ نہیں ہے اور مجھے اس کی ضرورت ہے۔ میں کیا کروں؟",
        },
        "kw": ["without cnic", "need my cnic", "no cnic", "don't have my cnic", "کارڈ نہیں"],
        "answer": {
            "en": """It depends on why you don't have it:
- **Lost or stolen:** apply for a reprint (see "Lost CNIC"). NADRA already holds your record
- **Expired:** apply for renewal
- **Applied but not received:** check the status in PakID or call 1777

Until the card arrives, some organisations (banks, for example) can verify you through NADRA's fingerprint or face verification instead. Ask the organisation what they accept.""",
            "ur": """یہ اس پر منحصر ہے کہ آپ کے پاس کارڈ کیوں نہیں:
- **گم یا چوری ہو گیا:** ری پرنٹ کے لیے درخواست دیں ("شناختی کارڈ گم ہو گیا" دیکھیں)۔ آپ کا ریکارڈ نادرا کے پاس پہلے سے موجود ہے
- **ایکسپائر ہو گیا:** تجدید کے لیے درخواست دیں
- **درخواست دی مگر کارڈ نہیں ملا:** پاک آئی ڈی میں سٹیٹس دیکھیں یا 1777 پر کال کریں

کارڈ آنے تک بعض ادارے (مثلاً بینک) نادرا کی انگلیوں یا چہرے کی تصدیق سے بھی آپ کی شناخت کر سکتے ہیں۔ متعلقہ ادارے سے پوچھیں کہ وہ کیا قبول کرتے ہیں۔""",
        },
        "chips": {
            "en": ["How do I get a replacement?", "What if I'm abroad?"],
            "ur": ["نیا کارڈ کیسے ملے گا؟", "اگر میں بیرونِ ملک ہوں؟"],
        },
        "sources": src("contact", "faqs"),
    },
    # -------------------------------------------------------- CNIC options
    "renew": {
        "title": {"en": "Renew CNIC", "ur": "شناختی کارڈ کی تجدید"},
        "question": {"en": "How do I renew my CNIC?", "ur": "میں اپنے شناختی کارڈ کی تجدید کیسے کروں؟"},
        "kw": ["renew", "renewal", "expired", "expiry", "تجدید", "ایکسپائر", "میعاد"],
        "answer": {
            "en": """When your card has expired or is about to, choose **Renewal** (not Reprint).
- Apply through the PakID app or portal, or at a NADRA Registration Centre. Biometrics may need a centre visit
- Keep your old CNIC or its number handy
- If a detail has changed (name, address, marital status), choose **Modification** so your record is updated too
- For fees and time, check NADRA's official page for the speed you choose""",
            "ur": """جب کارڈ ایکسپائر ہو جائے یا ہونے والا ہو تو **تجدید (Renewal)** کا انتخاب کریں، ری پرنٹ کا نہیں۔
- درخواست پاک آئی ڈی ایپ یا پورٹل سے، یا نادرا رجسٹریشن سینٹر میں دی جا سکتی ہے۔ بایومیٹرک کے لیے سینٹر جانا پڑ سکتا ہے
- اپنا پرانا شناختی کارڈ یا اس کا نمبر ساتھ رکھیں
- اگر نام، پتہ یا ازدواجی حیثیت جیسی کوئی تفصیل بدلی ہے تو **ترمیم (Modification)** چنیں تاکہ ریکارڈ بھی اپ ڈیٹ ہو
- فیس اور وقت کے لیے اپنی منتخب رفتار کے مطابق نادرا کا سرکاری صفحہ دیکھیں""",
        },
        "chips": {
            "en": ["Can I renew online?", "My card expired and I'm abroad"],
            "ur": ["کیا میں آن لائن تجدید کروا سکتا ہوں؟", "میرا کارڈ ایکسپائر ہو گیا اور میں بیرونِ ملک ہوں"],
        },
        "sources": src("cnic", "id_home"),
    },
    "lost": {
        "title": {"en": "Lost CNIC", "ur": "شناختی کارڈ گم ہو گیا"},
        "question": {
            "en": "My CNIC is lost. What should I do?",
            "ur": "میرا شناختی کارڈ گم ہو گیا ہے، مجھے کیا کرنا چاہیے؟",
        },
        "kw": ["lost", "stolen", "reprint", "gum", "kho", "گم", "کھو", "چوری", "دوبارہ"],
        "answer": {
            "en": """For a lost card, choose **Reprint (Lost)**. You normally don't need a new registration because NADRA already holds your record.
- Apply through the PakID app or portal, or at a NADRA Registration Centre
- Have your CNIC number ready (a photo or copy of the old card helps)
- If the card was stolen, a police report is sensible
- Once you apply, the old card is treated as invalid. If you find it, don't use it
- If your details have changed, choose Modification instead of Reprint

Check progress in the PakID inbox or on 1777.""",
            "ur": """گمشدہ کارڈ کے لیے **ری پرنٹ (گم شدہ)** کا انتخاب کریں۔ عام طور پر نئی رجسٹریشن کی ضرورت نہیں ہوتی کیونکہ آپ کا ریکارڈ نادرا کے پاس پہلے سے موجود ہے۔
- درخواست پاک آئی ڈی ایپ یا پورٹل سے، یا نادرا رجسٹریشن سینٹر میں دیں
- اپنا شناختی کارڈ نمبر تیار رکھیں (پرانے کارڈ کی تصویر یا کاپی ہو تو مددگار ہے)
- اگر کارڈ چوری ہوا ہو تو پولیس رپورٹ کروانا مناسب ہے
- درخواست دینے کے بعد پرانا کارڈ ناقابلِ استعمال سمجھا جاتا ہے۔ مل جائے تو استعمال نہ کریں
- اگر تفصیلات بدلی ہیں تو ری پرنٹ کے بجائے ترمیم (Modification) چنیں

پیش رفت پاک آئی ڈی ان باکس میں یا 1777 پر دیکھیں۔""",
        },
        "chips": {
            "en": ["Do I need a police report?", "What if I'm abroad?"],
            "ur": ["کیا مجھے پولیس رپورٹ چاہیے؟", "اگر میں بیرونِ ملک ہوں؟"],
        },
        "sources": src("faqs", "contact", "lost_guide"),
    },
    "damaged": {
        "title": {"en": "Damaged CNIC", "ur": "خراب شناختی کارڈ"},
        "question": {
            "en": "My CNIC is damaged. What should I do?",
            "ur": "میرا شناختی کارڈ خراب ہو گیا ہے، مجھے کیا کرنا چاہیے؟",
        },
        "kw": ["damaged", "broken", "torn", "worn", "خراب", "پھٹ", "ٹوٹ"],
        "answer": {
            "en": """If the card is damaged but not expired and your details are correct, the usual category is **Reprint**, the same route as a lost card.
- Card expired: choose Renewal
- A detail is wrong or needs changing: choose Modification
- Apply through the PakID app or at a NADRA Registration Centre

Confirm the right category with a NADRA centre or on 1777 before you pay.""",
            "ur": """اگر کارڈ خراب ہے مگر ایکسپائر نہیں ہوا اور تفصیلات درست ہیں تو عموماً **ری پرنٹ** کا زمرہ چنا جاتا ہے، یعنی وہی راستہ جو گمشدہ کارڈ کا ہے۔
- کارڈ ایکسپائر ہو چکا ہو تو تجدید چنیں
- کوئی تفصیل غلط ہو یا بدلنی ہو تو ترمیم (Modification) چنیں
- درخواست پاک آئی ڈی ایپ یا نادرا رجسٹریشن سینٹر سے دی جا سکتی ہے

ادائیگی سے پہلے درست زمرہ نادرا سینٹر یا 1777 سے تصدیق کر لیں۔""",
        },
        "chips": {
            "en": ["What is the difference between reprint and modification?", "Can I still use a damaged card?"],
            "ur": ["ری پرنٹ اور ترمیم میں کیا فرق ہے؟", "کیا میں خراب کارڈ استعمال کر سکتا ہوں؟"],
        },
        "sources": src("faqs", "lost_guide"),
    },
    "update-info": {
        "title": {"en": "Update or correct information", "ur": "معلومات میں تبدیلی یا درستی"},
        "question": {
            "en": "How do I change or correct information on my CNIC?",
            "ur": "میں اپنے شناختی کارڈ کی معلومات کیسے تبدیل یا درست کروں؟",
        },
        "kw": ["change", "correct", "modify", "modification", "update", "name", "address", "marital", "date of birth",
               "تبدیل", "درست", "ترمیم", "نام", "پتہ", "تاریخِ پیدائش", "پیدائش"],
        "answer": {
            "en": """A change to your name, address, marital status, photo or other details is called a **Modification**.
- Depending on the change, NADRA asks for supporting documents (for example a marriage certificate for marital status), and biometric verification may be needed
- Some corrections, such as date of birth, involve other authorities too, for example the Union Council
- You can apply at a NADRA centre or through the PakID app

Tell me which detail you want to change and I'll share what NADRA publishes for it.""",
            "ur": """نام، پتہ، ازدواجی حیثیت، تصویر یا دیگر تفصیلات میں تبدیلی **ترمیم (Modification)** کہلاتی ہے۔
- تبدیلی کے مطابق نادرا معاون کاغذات مانگتا ہے (مثلاً ازدواجی حیثیت کے لیے نکاح نامہ)، اور بایومیٹرک تصدیق بھی درکار ہو سکتی ہے
- بعض درستیوں میں، جیسے تاریخِ پیدائش، دوسرے ادارے بھی شامل ہوتے ہیں، مثلاً یونین کونسل
- درخواست نادرا سینٹر یا پاک آئی ڈی سے دی جا سکتی ہے

بتائیں کون سی تفصیل بدلنی ہے، میں اس کے لیے نادرا کی شائع کردہ معلومات بتا دوں گا۔""",
        },
        "chips": {
            "en": ["My date of birth is wrong", "I got married and want to update my record"],
            "ur": ["میری تاریخِ پیدائش غلط ہے", "میری شادی ہو گئی ہے، ریکارڈ اپ ڈیٹ کروانا ہے"],
        },
        "sources": src("cnic", "faqs"),
    },
    "cnic-general": {
        "title": {"en": "CNIC questions", "ur": "شناختی کارڈ سے متعلق سوالات"},
        "question": None,
        "kw": [],
        "answer": None,
        "chips": {
            "en": [
                "Can I change my father's name?",
                "Why is my date of birth wrong?",
                "Can I renew my CNIC online?",
            ],
            "ur": [
                "کیا میں والد کا نام تبدیل کروا سکتا ہوں؟",
                "میری تاریخِ پیدائش غلط کیوں ہے؟",
                "کیا میں آن لائن تجدید کروا سکتا ہوں؟",
            ],
        },
        "sources": [],
    },
}

# ---------------------------------------------------------------------------
# Home and CNIC page layouts: (topic slug, card label, icon)
# ---------------------------------------------------------------------------
POPULAR = [
    ("first-cnic", {"en": "How do I get my first CNIC?", "ur": "میں اپنا پہلا شناختی کارڈ کیسے بنواؤں؟"}),
    ("fees-processing", {"en": "What are the fees and processing times?", "ur": "فیس اور پروسیسنگ کا وقت کتنا ہے؟"}),
    ("documents", {"en": "What documents do I need?", "ur": "مجھے کون سے کاغذات درکار ہیں؟"}),
    ("biometric-iris", {"en": "Why am I asked for biometric or iris verification?", "ur": "مجھ سے بایومیٹرک یا آئرس تصدیق کیوں مانگی جا رہی ہے؟"}),
    ("id-types", {"en": "CNIC, NICOP or POC: which card is for me?", "ur": "سی این آئی سی، نکوپ یا پی او سی: میرے لیے کون سا؟"}),
    ("pensioner", {"en": "What NADRA services are there for pensioners?", "ur": "پنشنرز کے لیے نادرا کی کون سی خدمات ہیں؟"}),
]

PROBLEMS = [
    ("rejected", {"en": "My application was rejected", "ur": "میری درخواست مسترد ہو گئی"}, ":material/cancel:"),
    ("refused", {"en": "NADRA refused my service", "ur": "نادرا نے سروس دینے سے انکار کیا"}, ":material/block:"),
    ("delayed", {"en": "My application is delayed or stuck", "ur": "میری درخواست رکی ہوئی ہے"}, ":material/hourglass_empty:"),
    ("verify-problem", {"en": "My biometric verification isn't working", "ur": "میری بایومیٹرک تصدیق نہیں ہو رہی"}, ":material/fingerprint:"),
    ("missing-doc", {"en": "I don't have the required document", "ur": "میرے پاس مطلوبہ کاغذ نہیں"}, ":material/description:"),
    ("no-cnic", {"en": "I don't have my CNIC when I need it", "ur": "ضرورت کے وقت میرے پاس کارڈ نہیں"}, ":material/badge:"),
]

CNIC_OPTIONS = [
    ("first-cnic", {"en": "First CNIC", "ur": "پہلا شناختی کارڈ"}, ":material/badge:"),
    ("renew", {"en": "Renew CNIC", "ur": "کارڈ کی تجدید"}, ":material/autorenew:"),
    ("lost", {"en": "Lost CNIC", "ur": "کارڈ گم ہو گیا"}, ":material/search_off:"),
    ("damaged", {"en": "Damaged CNIC", "ur": "کارڈ خراب ہو گیا"}, ":material/broken_image:"),
    ("update-info", {"en": "Update or correct information", "ur": "معلومات میں تبدیلی یا درستی"}, ":material/edit:"),
    ("verify-problem", {"en": "Can't verify my CNIC", "ur": "کارڈ کی تصدیق نہیں ہو رہی"}, ":material/fingerprint:"),
    ("cnic-general", {"en": "Other CNIC questions", "ur": "شناختی کارڈ کے دیگر سوالات"}, ":material/forum:"),
]

# ---------------------------------------------------------------------------
# Services directory
# ---------------------------------------------------------------------------
SERVICE_GROUPS = {
    "identity": {"en": "Identity documents", "ur": "شناختی دستاویزات"},
    "certificates": {"en": "Certificates", "ur": "سرٹیفکیٹس"},
    "verification": {"en": "Verification", "ur": "تصدیق"},
    "digital": {"en": "Digital services", "ur": "ڈیجیٹل خدمات"},
}

SERVICES = [
    {
        "key": "cnic", "group": "identity", "topic": "first-cnic",
        "name": {"en": "CNIC", "ur": "شناختی کارڈ (CNIC)"},
        "blurb": {"en": "Identity card for adult Pakistani citizens.", "ur": "پاکستانی بالغ شہریوں کا شناختی کارڈ۔"},
        "question": {"en": "What is the CNIC and how do I apply?", "ur": "شناختی کارڈ کیا ہے اور میں درخواست کیسے دوں؟"},
    },
    {
        "key": "nicop", "group": "identity", "topic": "id-types",
        "name": {"en": "NICOP", "ur": "نکوپ (NICOP)"},
        "blurb": {"en": "Identity card for Pakistani citizens living abroad.", "ur": "بیرونِ ملک رہنے والے پاکستانی شہریوں کا شناختی کارڈ۔"},
        "question": {"en": "What is a NICOP and who can apply?", "ur": "نکوپ کیا ہے اور کون درخواست دے سکتا ہے؟"},
    },
    {
        "key": "poc", "group": "identity", "topic": "id-types",
        "name": {"en": "POC", "ur": "پی او سی (POC)"},
        "blurb": {"en": "Pakistan Origin Card for people of Pakistani origin who are not citizens.", "ur": "پاکستانی نژاد افراد کے لیے پاکستان اوریجن کارڈ جو شہری نہیں ہیں۔"},
        "question": {"en": "What is the POC card and who is it for?", "ur": "پی او سی کارڈ کیا ہے اور کس کے لیے ہے؟"},
    },
    {
        "key": "crc", "group": "identity", "topic": "id-types",
        "name": {"en": "CRC (B-Form)", "ur": "سی آر سی (ب فارم)"},
        "blurb": {"en": "Registration certificate for children under 18.", "ur": "18 سال سے کم عمر بچوں کا رجسٹریشن سرٹیفکیٹ۔"},
        "question": {"en": "What is a CRC (B-Form) and what is needed for it?", "ur": "سی آر سی (ب فارم) کیا ہے اور اس کے لیے کیا چاہیے؟"},
    },
    {
        "key": "frc", "group": "certificates", "topic": "id-types",
        "name": {"en": "FRC", "ur": "ایف آر سی (FRC)"},
        "blurb": {"en": "A certificate listing family members registered together with NADRA.", "ur": "نادرا میں ایک ساتھ رجسٹرڈ خاندان کے افراد کی فہرست کا سرٹیفکیٹ۔"},
        "question": {"en": "What is an FRC and what is it used for?", "ur": "ایف آر سی کیا ہے اور کس کام آتا ہے؟"},
    },
    {
        "key": "biometric", "group": "verification", "topic": "biometric-iris",
        "name": {"en": "Biometric verification", "ur": "بایومیٹرک تصدیق"},
        "blurb": {"en": "Confirming identity with fingerprints, face or iris.", "ur": "انگلیوں، چہرے یا آئرس سے شناخت کی تصدیق۔"},
        "question": {"en": "How does biometric verification work?", "ur": "بایومیٹرک تصدیق کیسے کام کرتی ہے؟"},
    },
    {
        "key": "pol", "group": "verification", "topic": "pensioner",
        "name": {"en": "Proof of Life", "ur": "پروف آف لائف"},
        "blurb": {"en": "Pensioners confirm they are alive so pension payments continue.", "ur": "پنشنرز تصدیق کرتے ہیں کہ وہ زندہ ہیں تاکہ پنشن جاری رہے۔"},
        "question": {"en": "How do pensioners complete Proof of Life?", "ur": "پنشنرز پروف آف لائف کیسے مکمل کریں؟"},
    },
    {
        "key": "pakid", "group": "digital", "topic": None,
        "name": {"en": "PakID app", "ur": "پاک آئی ڈی ایپ"},
        "blurb": {"en": "NADRA's official mobile app for identity registration, updates and service tracking.", "ur": "شناختی رجسٹریشن، اپ ڈیٹس اور خدمات کی ٹریکنگ کے لیے نادرا کی سرکاری موبائل ایپ۔"},
        "question": {"en": "What can I do with the PakID app?", "ur": "پاک آئی ڈی ایپ سے میں کیا کر سکتا ہوں؟"},
    },
]

# ---------------------------------------------------------------------------
# Extra knowledge snippets (used as context for follow-up questions).
# Topic answers above are added automatically at the bottom of this file.
# ---------------------------------------------------------------------------
_EXTRAS = [
    {
        "id": "contact", "topic": None,
        "kw": ["helpline", "contact", "support", "customer", "phone", "number", "email", "complaint", "complain",
               "escalate", "1777", "call", "شکایت", "ہیلپ", "رابطہ", "نمبر", "سپورٹ", "کسٹمر"],
        "text": {
            "en": "NADRA helpline: 1777 from mobile phones in Pakistan; +92 51 111 786 100 for landlines and overseas callers. Email: csd@nadra.gov.pk. Complaints portal: complaints.nadra.gov.pk. NADRA says complaints from all channels are logged in one central system, which escalates complaints that are not resolved in time. The PakID app also offers a quick chat option. This assistant cannot contact NADRA for you.",
            "ur": "نادرا ہیلپ لائن: پاکستان میں موبائل فون سے 1777؛ لینڈ لائن اور بیرونِ ملک سے کال کرنے والوں کے لیے +92 51 111 786 100۔ ای میل: csd@nadra.gov.pk۔ شکایات کا پورٹل: complaints.nadra.gov.pk۔ نادرا کے مطابق تمام ذرائع سے آنے والی شکایات ایک مرکزی نظام میں درج ہوتی ہیں، جو بروقت حل نہ ہونے والی شکایات کو آگے بھیجتا ہے۔ پاک آئی ڈی ایپ میں فوری چیٹ کی سہولت بھی ہے۔ یہ اسسٹنٹ آپ کی طرف سے نادرا سے رابطہ نہیں کر سکتا۔",
        },
        "sources": src("contact", "complaint_pr", "complaints"),
    },
    {
        "id": "status", "topic": None,
        "kw": ["status", "track", "tracking", "inbox", "where is my", "سٹیٹس", "ٹریک", "صورتحال"],
        "text": {
            "en": "This assistant cannot see or track applications. NADRA's contact page says you can check your application status from the application inbox in the PakID app, and the helpline (1777) can also help. Keep your tracking ID ready, and never type it into this chat.",
            "ur": "یہ اسسٹنٹ درخواستوں کو دیکھ یا ٹریک نہیں کر سکتا۔ نادرا کے رابطہ صفحے کے مطابق آپ پاک آئی ڈی ایپ کے ایپلیکیشن ان باکس میں اپنی درخواست کی صورتحال دیکھ سکتے ہیں، اور ہیلپ لائن (1777) بھی مدد کر سکتی ہے۔ اپنی ٹریکنگ آئی ڈی تیار رکھیں، مگر اسے اس چیٹ میں نہ لکھیں۔",
        },
        "sources": src("contact"),
    },
    {
        "id": "birth-cert", "topic": None,
        "kw": ["birth certificate", "birth", "union council", "برتھ", "سرٹیفکیٹ", "یونین کونسل", "پیدائش کا"],
        "text": {
            "en": "For a first CNIC, NADRA's public CNIC page lists a computerised birth certificate (issued by the Union Council, Municipal Committee or Cantonment) or a citizenship/naturalization certificate. If you have no blood relative, it also mentions a biometric witness (an ID card holder) with an undertaking, for some cases only. Ask a NADRA centre which option applies to you. A missing certificate is normally re-obtained from the office that issued it.",
            "ur": "پہلے شناختی کارڈ کے لیے نادرا کا عوامی صفحہ کمپیوٹرائزڈ برتھ سرٹیفکیٹ (یونین کونسل، میونسپل کمیٹی یا کنٹونمنٹ کا جاری کردہ) یا شہریت / نیچرلائزیشن سرٹیفکیٹ درج کرتا ہے۔ اگر کوئی خونی رشتہ دار نہ ہو تو بعض صورتوں میں شناختی کارڈ رکھنے والے گواہ کی بایومیٹرک تصدیق اور انڈرٹیکنگ کا ذکر بھی ہے۔ نادرا سینٹر سے پوچھیں کہ آپ کے لیے کون سا آپشن لاگو ہوتا ہے۔ گمشدہ سرٹیفکیٹ عموماً اسی دفتر سے دوبارہ لیا جاتا ہے جس نے جاری کیا تھا۔",
        },
        "sources": src("cnic"),
    },
    {
        "id": "face-verify", "topic": None,
        "kw": ["face", "facial", "iris", "fingerprint", "elderly", "old age", "چہرے", "آئرس", "انگلی", "انگلیوں", "بزرگ"],
        "text": {
            "en": "NADRA has said it offers alternative verification for people whose fingerprints will not verify, including through the PakID app and in person at NADRA centres. News reports say facial recognition and iris scans are now recognised as biometric identifiers, and that NADRA centres can issue a face-based verification certificate. Details, fees and validity can change, so confirm with NADRA.",
            "ur": "نادرا نے کہا ہے کہ جن لوگوں کی انگلیوں کے نشانات کی تصدیق نہیں ہوتی ان کے لیے متبادل تصدیق موجود ہے، جو پاک آئی ڈی ایپ اور نادرا سینٹرز میں بالمشافہ دونوں طرح ممکن ہے۔ خبروں کے مطابق چہرے اور آئرس کی شناخت اب بایومیٹرک شناخت کے طور پر تسلیم شدہ ہے، اور نادرا سینٹرز چہرے پر مبنی تصدیقی سرٹیفکیٹ جاری کر سکتے ہیں۔ تفصیل، فیس اور مدت تبدیل ہو سکتی ہے، اس لیے نادرا سے تصدیق کر لیں۔",
        },
        "sources": src("idtech", "face_news", "biometric_pr"),
    },
    {
        "id": "abroad", "topic": None,
        "kw": ["abroad", "overseas", "outside pakistan", "foreign", "بیرون", "بیرونِ", "اوورسیز", "بیرونی"],
        "text": {
            "en": "From abroad, use +92 51 111 786 100 (1777 is NADRA's line for mobile users). NADRA says its online PakID services are available in more than 190 countries, and overseas applicants can apply through the PakID app. Biometric steps may still need a visit to a NADRA centre or a Pakistani mission, so confirm which applies to your service.",
            "ur": "بیرونِ ملک سے +92 51 111 786 100 استعمال کریں (1777 نادرا کی موبائل صارفین کے لیے لائن ہے)۔ نادرا کے مطابق اس کی آن لائن پاک آئی ڈی خدمات 190 سے زیادہ ممالک میں دستیاب ہیں، اور بیرونِ ملک درخواست دہندگان پاک آئی ڈی ایپ سے درخواست دے سکتے ہیں۔ بایومیٹرک مراحل کے لیے پھر بھی نادرا سینٹر یا پاکستانی مشن جانا پڑ سکتا ہے، اس لیے اپنی خدمت کے لیے تصدیق کر لیں۔",
        },
        "sources": src("complaint_pr", "contact"),
    },
    {
        "id": "child-crc", "topic": None,
        "kw": ["b-form", "b form", "bform", "crc", "child", "children", "ب فارم", "بچے", "بچوں", "بچہ"],
        "text": {
            "en": "Children under 18 are registered with a CRC (B-Form). Community guides report that you need the child's computerised birth certificate (from the Union Council) and the original, valid CNICs of both parents, and that older children need a photo or biometric capture at a NADRA centre. B-Form rules have been changing, so confirm the current requirements with NADRA.",
            "ur": "18 سال سے کم عمر بچوں کی رجسٹریشن سی آر سی (ب فارم) سے ہوتی ہے۔ کمیونٹی گائیڈز کے مطابق بچے کا کمپیوٹرائزڈ برتھ سرٹیفکیٹ (یونین کونسل سے) اور دونوں والدین کے اصل اور کارآمد شناختی کارڈ درکار ہوتے ہیں، اور بڑے بچوں کی تصویر یا بایومیٹرک نادرا سینٹر میں لی جاتی ہے۔ ب فارم کے قواعد بدلتے رہے ہیں، اس لیے موجودہ تقاضے نادرا سے تصدیق کر لیں۔",
        },
        "sources": src("crc_guide"),
    },
    {
        "id": "pension-help", "topic": None,
        "kw": ["family member", "bedridden", "mobile unit", "at home", "خاندان", "گھر", "بستر", "معذور"],
        "text": {
            "en": "News reports say pensioners who cannot use the app themselves can get Proof of Life help through a family member after identity verification, and that NADRA offers mobile services for elderly, bedridden or low-mobility pensioners. Details may change, so confirm with NADRA on 1777.",
            "ur": "خبروں کے مطابق جو پنشنرز خود ایپ استعمال نہیں کر سکتے وہ شناخت کی تصدیق کے بعد خاندان کے کسی فرد کے ذریعے پروف آف لائف کی سہولت لے سکتے ہیں، اور نادرا بزرگ، بستر پر پڑے یا کم چل پھر سکنے والے پنشنرز کے لیے موبائل سروس بھی دیتا ہے۔ تفصیل بدل سکتی ہے، اس لیے نادرا سے 1777 پر تصدیق کر لیں۔",
        },
        "sources": src("pension_ausaf", "pension_geo"),
    },
    {
        "id": "parent-expired", "topic": None,
        "kw": ["expired", "parent", "father", "mother", "والد", "والدہ", "ایکسپائر", "امی", "ابو"],
        "text": {
            "en": "An expired parent CNIC is a commonly reported reason for delays or refusals, because the parent is often the person who verifies the application. The parent would generally need to renew their card first. Confirm with NADRA.",
            "ur": "والدین میں سے کسی کا ایکسپائر شناختی کارڈ تاخیر یا انکار کی عام رپورٹ شدہ وجہ ہے، کیونکہ اکثر والدین ہی درخواست کی تصدیق کرتے ہیں۔ عموماً پہلے متعلقہ والد یا والدہ کو اپنے کارڈ کی تجدید کروانی ہوگی۔ نادرا سے تصدیق کر لیں۔",
        },
        "sources": src("new_cnic_guide"),
    },
    {
        "id": "pakid", "topic": None,
        "kw": ["pakid", "pak id", "pak-id", "app", "mobile app", "online", "پاک آئی ڈی", "ایپ", "آن لائن"],
        "text": {
            "en": "PakID is NADRA's official mobile app for identity registration, updates and tracking your services. NADRA says you can get a CNIC, FRC or other identity documents through NADRA centres or the PakID app, but biometric verification and photographs may still need a visit to a Registration Centre. NADRA's contact page also mentions a quick chat option in PakID and application status in your application inbox.",
            "ur": "پاک آئی ڈی نادرا کی سرکاری موبائل ایپ ہے جو شناختی رجسٹریشن، اپ ڈیٹس اور خدمات کی ٹریکنگ کے لیے ہے۔ نادرا کے مطابق آپ شناختی کارڈ، ایف آر سی یا دیگر شناختی دستاویزات نادرا سینٹرز یا پاک آئی ڈی ایپ سے حاصل کر سکتے ہیں، لیکن بایومیٹرک تصدیق اور تصویر کے لیے پھر بھی رجسٹریشن سینٹر جانا پڑ سکتا ہے۔ نادرا کے رابطہ صفحے میں پاک آئی ڈی میں فوری چیٹ اور ایپلیکیشن ان باکس میں سٹیٹس دیکھنے کا بھی ذکر ہے۔",
        },
        "sources": src("id_home", "cnic", "contact"),
    },
]

# Build the searchable knowledge base: every curated topic answer + the extras.
KB = []
for _slug, _t in TOPICS.items():
    if _t.get("answer"):
        KB.append({
            "id": _slug,
            "topic": _slug,
            "kw": _t["kw"],
            "text": _t["answer"],
            "sources": _t["sources"],
        })
KB.extend(_EXTRAS)
